name: Publish NuGet Package

on:
  release:
    types: [ "published" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build .Net 9.0
        run: dotnet build --configuration Release --no-restore --framework net9.0

      - name: Pack
        run: dotnet pack  --configuration Release --no-build --output ./nupkgs

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "nupkgs/*.nupkg" -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
